version: '3'
services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - 6379
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "PING"]
  #     interval: 2s
  #     retries: 5
  reactreduxsagawebapp:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:3200
    environment:
      - NODE_ENV=prod
